# PARTE DO PROFESSOR

In [6]:
import pandas as pd

df = pd.read_csv('../Data_Layer/raw/Complete_Pokedex_V1.1.csv')

In [7]:
df.head()

,pokedex_number,pokemon_name,type_1,type_2,ability_1,ability_2,ability_3,number_pokemon_with_typing,primary_color,shape,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,Grass,Poison,Overgrow,Chlorophyll,NaN,15,Green,Quadruped,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,Grass,Poison,Overgrow,Chlorophyll,NaN,15,Green,Quadruped,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Mega Venusaur,Grass,Poison,Thick Fat,NaN,NaN,15,Green,Quadruped,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,Venusaur,Grass,Poison,Overgrow,Chlorophyll,NaN,15,Green,Quadruped,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,3,Venusaur Gmax,Grass,Poison,Overgrow,Chlorophyll,NaN,15,Green,Quadruped,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5

In [8]:
df.columns

Index(['pokedex_number', 'pokemon_name', 'type_1', 'type_2', 'ability_1',
       'ability_2', 'ability_3', 'number_pokemon_with_typing', 'primary_color',
       'shape', 'height', 'weight', 'bmi', 'hit_points', 'attack', 'defense',
       'special_attack', 'special_defense', 'speed', 'total_stats', 'mean',
       'standard_deviation', 'capture_rate', 'generation', 'base_happiness',
       'base_experience', 'exp_type', 'exp_to_level_100', 'can_evolve',
       'evolves_from', 'final_evolution', 'mega_evolution', 'is_default',
       'baby_pokemon', 'alolan_form', 'galarian_form', 'forms_switchable',
       'legendary', 'mythical', 'genderless', 'female_rate', 'genus',
       'egg_group_1', 'egg_group_2', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fighting', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy'],
      dtype='object')

In [9]:
df['type_1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Dark', 'Poison',
       'Electric', 'Ice', 'Ground', 'Fairy', 'Steel', 'Fighting',
       'Psychic', 'Rock', 'Ghost', 'Dragon', 'Flying'], dtype=object)

In [10]:
df.columns

Index(['pokedex_number', 'pokemon_name', 'type_1', 'type_2', 'ability_1',
       'ability_2', 'ability_3', 'number_pokemon_with_typing', 'primary_color',
       'shape', 'height', 'weight', 'bmi', 'hit_points', 'attack', 'defense',
       'special_attack', 'special_defense', 'speed', 'total_stats', 'mean',
       'standard_deviation', 'capture_rate', 'generation', 'base_happiness',
       'base_experience', 'exp_type', 'exp_to_level_100', 'can_evolve',
       'evolves_from', 'final_evolution', 'mega_evolution', 'is_default',
       'baby_pokemon', 'alolan_form', 'galarian_form', 'forms_switchable',
       'legendary', 'mythical', 'genderless', 'female_rate', 'genus',
       'egg_group_1', 'egg_group_2', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fighting', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy'],
      dtype='object')

In [11]:
df_temp = df[df['type_1'] == 'Grass']

In [12]:
df_tipo = df.drop(columns = ['pokedex_number', 'pokemon_name', 'ability_1',
       'ability_2', 'ability_3', 'number_pokemon_with_typing', 'primary_color',
       'shape', 'height', 'weight', 'bmi', 'hit_points', 'attack', 'defense',
       'special_attack', 'special_defense', 'speed', 'total_stats', 'mean',
       'standard_deviation', 'capture_rate', 'generation', 'base_happiness',
       'base_experience', 'exp_type', 'exp_to_level_100', 'can_evolve',
       'evolves_from', 'final_evolution', 'mega_evolution', 'is_default',
       'baby_pokemon', 'alolan_form', 'galarian_form', 'forms_switchable',
       'legendary', 'mythical', 'genderless', 'female_rate', 'genus',
       'egg_group_1', 'egg_group_2', 'egg_cycles',])

In [13]:
df_tipo

,type_1,type_2,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,Ice,NaN,1.0,2.0,1.0,1.0,1.00,0.5,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
1114,Ghost,NaN,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
1115,Psychic,Grass,1.0,2.0,0.5,0.5,0.50,2.0,0.5,2.0,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0
1116,Psychic,Ice,1.0,2.0,1.0,1.0,1.00,0.5,1.0,1.0,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0
1117,Psychic,Ghost,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0

In [14]:
df_tipo = df_tipo.fillna('')

In [15]:
df_tipo['Tipo'] = df_tipo['type_1'] + ' ' + df_tipo['type_2']

In [16]:
df_tipo

,type_1,type_2,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,Tipo
0,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,Grass Poison
1,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,Grass Poison
2,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,Grass Poison
3,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,Grass Poison
4,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,Grass Poison
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,Ice,,1.0,2.0,1.0,1.0,1.00,0.5,2.0,1.0,...,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,Ice
1114,Ghost,,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,...,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0,Ghost
1115,Psychic,Grass,1.0,2.0,0.5,0.5,0.50,2.0,0.5,2.0,...,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0,Psychic Grass
1116,Psychic,Ice,1.0,2.0,1.0,1.0,1.00,0.5,1.0,1.0,...,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0,Psychic Ice
1117,Psychic,Ghost,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,...,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0,Psychic Ghost

In [17]:
df_tipo = df_tipo.drop_duplicates()

In [18]:
df_tipo.columns

Index(['type_1', 'type_2', 'against_normal', 'against_fire', 'against_water',
       'against_electric', 'against_grass', 'against_ice', 'against_fighting',
       'against_poison', 'against_ground', 'against_flying', 'against_psychic',
       'against_bug', 'against_rock', 'against_ghost', 'against_dragon',
       'against_dark', 'against_steel', 'against_fairy', 'Tipo'],
      dtype='object')

In [19]:
df_tipo = df_tipo[['Tipo','type_1', 'type_2', 'against_normal', 'against_fire', 'against_water',
       'against_electric', 'against_grass', 'against_ice', 'against_fighting',
       'against_poison', 'against_ground', 'against_flying', 'against_psychic',
       'against_bug', 'against_rock', 'against_ghost', 'against_dragon',
       'against_dark', 'against_steel', 'against_fairy']]

In [20]:
df_tipo.reset_index(inplace = True,drop=True)

In [21]:
df_tipo.head()

,Tipo,type_1,type_2,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,Grass Poison,Grass,Poison,1.0,2.00,0.5,0.5,0.25,2.0,0.5,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
1,Fire,Fire,,1.0,0.50,2.0,1.0,0.50,0.5,1.0,...,2.0,1.0,1.0,0.50,2.0,1.0,1.0,1.0,0.5,0.5
2,Fire Flying,Fire,Flying,1.0,0.50,2.0,2.0,0.25,1.0,0.5,...,0.0,1.0,1.0,0.25,4.0,1.0,1.0,1.0,0.5,0.5
3,Fire Dragon,Fire,Dragon,1.0,0.25,1.0,0.5,0.25,1.0,1.0,...,2.0,1.0,1.0,0.50,2.0,1.0,2.0,1.0,0.5,1.0
4,Water,Water,,1.0,0.50,0.5,2.0,2.00,0.5,1.0,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0