# Consultas e Visualizações no Banco

Neste notebook são demonstrados os comandos SELECT para realizar consultas e visualizações no banco de dados que está em um contêiner do Docker.

#### Visualização da tabela pokemon

In [16]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost",
            port=5432,
            database="silver_db",
            user="silver_user",
            password="silver_password"
        )
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

# cria o cursor
cursor = conexao.cursor()

cursor.execute("""
    SELECT * FROM pokemon; 
""")

# visualizar os resultados
dados = cursor.fetchall() # Captura os resultados 
colunas = [desc[0] for desc in cursor.description] # Captura os nomes das colunas
df = pd.DataFrame(dados, columns=colunas) # Cria um DataFrame para exibir
display(df) # Exibe o DataFrame 


# Fechando conexão
cursor.close()
conexao.close()

,pokedex_number,pokemon_name,type_1,type_2,height,weight,hit_points,attack,defense,total_stats,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,Grass,Poison,0.7,6.9,45,49,49,318,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,Grass,Poison,1.0,13.0,60,62,63,405,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Mega Venusaur,Grass,Poison,2.4,155.5,80,100,123,625,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,4,Charmander,Fire,Indefinido,0.6,8.5,39,52,43,309,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
4,5,Charmeleon,Fire,Indefinido,1.1,19.0,58,64,58,405,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,894,Regieleki,Electric,Indefinido,1.2,145.0,80,100,50,580,...,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
894,895,Regidrago,Dragon,Indefinido,2.1,200.0,200,100,50,580,...,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0
895,896,Glastrier,Ice,Indefinido,2.2,800.0,100,145,130,580,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
896,897,Spectrier,Ghost,Indefinido,2.0,44.5,100,65,60,580,...,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
897,898,Calyrex,Psychic,Grass,1.1,7.7,100,80,80,500,...,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0

#### Consulta dos nomes dos pokémons presentes na tabela pokemon

In [17]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost",
            port=5432,
            database="silver_db",
            user="silver_user",
            password="silver_password"
        )
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

# cria o cursor
cursor = conexao.cursor()

cursor.execute("""
    SELECT pokemon_name FROM pokemon; 
""")
# visualizar os resultados
dados = cursor.fetchall() # Captura os resultados 
colunas = [desc[0] for desc in cursor.description] # Captura os nomes das colunas
df = pd.DataFrame(dados, columns=colunas) # Cria um DataFrame para exibir
display(df) # Exibe o DataFrame 

# Fechando conexão
cursor.close()
conexao.close()

      pokemon_name
0        Bulbasaur
1          Ivysaur
2    Mega Venusaur
3       Charmander
4       Charmeleon
..             ...
893      Regieleki
894      Regidrago
895      Glastrier
896      Spectrier
897        Calyrex

[898 rows x 1 columns]